/*


                         This page appears after successfull AdminLogin

 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guiproject;

/**
 *
 * @author 59510
 */
public class AdminWork extends javax.swing.JFrame {

    /**
     * Creates new form AdminWork
     */
    public AdminWork() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AdminTasksLabel = new javax.swing.JLabel();
        AdminTask1ManageMovies = new javax.swing.JButton();
        AdminTask2UpdatingTicketPrices = new javax.swing.JButton();
        LogoutBtnForAdmin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminTasksLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AdminTasksLabel.setForeground(new java.awt.Color(255, 255, 255));
        AdminTasksLabel.setText("Admin's Dashboard");
        AdminTasksLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(AdminTasksLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        AdminTask1ManageMovies.setBackground(new java.awt.Color(0, 255, 102));
        AdminTask1ManageMovies.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AdminTask1ManageMovies.setText("Manage Movies");
        jPanel1.add(AdminTask1ManageMovies, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 200, -1));

        AdminTask2UpdatingTicketPrices.setBackground(new java.awt.Color(0, 255, 102));
        AdminTask2UpdatingTicketPrices.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AdminTask2UpdatingTicketPrices.setText("Update Ticket Prices");
        jPanel1.add(AdminTask2UpdatingTicketPrices, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 200, -1));

        LogoutBtnForAdmin.setBackground(new java.awt.Color(255, 51, 51));
        LogoutBtnForAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LogoutBtnForAdmin.setText("Logout");
        jPanel1.add(LogoutBtnForAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\59510\\Downloads\\required4.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminWork().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminTask1ManageMovies;
    private javax.swing.JButton AdminTask2UpdatingTicketPrices;
    private javax.swing.JLabel AdminTasksLabel;
    private javax.swing.JButton LogoutBtnForAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
