/*



                        This page will appear after clicking the Adimn>ManageMovies Btn



 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guiproject;

/**
 *
 * @author 59510
 */
public class aManageMovies extends javax.swing.JFrame {

    /**
     * Creates new form aManageMovies
     */
    public aManageMovies() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelEnterMovieNameToDelete = new javax.swing.JLabel();
        TxtFieldMovieNameToDelete = new javax.swing.JTextField();
        LogoToShowADDEDsuccessfullyORnot = new javax.swing.JLabel();
        LabelEnterMovieNameYouWantToAdd = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        TextFieldMovieToAdd = new javax.swing.JTextField();
        OKbtnToAddMovie = new javax.swing.JButton();
        SuccessfulORnot = new javax.swing.JLabel();
        LabelAvailableMoviesList = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AvailableMoviesList = new javax.swing.JTextArea();
        MoveToAdminTaskPagebtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelEnterMovieNameToDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelEnterMovieNameToDelete.setForeground(new java.awt.Color(255, 255, 255));
        LabelEnterMovieNameToDelete.setText("Enter the name of the movie you want to delete.");
        LabelEnterMovieNameToDelete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(LabelEnterMovieNameToDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        TxtFieldMovieNameToDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldMovieNameToDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(TxtFieldMovieNameToDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 220, -1));

        LogoToShowADDEDsuccessfullyORnot.setForeground(new java.awt.Color(255, 255, 255));
        LogoToShowADDEDsuccessfullyORnot.setText("Result");
        jPanel1.add(LogoToShowADDEDsuccessfullyORnot, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        LabelEnterMovieNameYouWantToAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelEnterMovieNameYouWantToAdd.setForeground(new java.awt.Color(255, 255, 255));
        LabelEnterMovieNameYouWantToAdd.setText("Enter the name of the movie you want to add.");
        LabelEnterMovieNameYouWantToAdd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(LabelEnterMovieNameYouWantToAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 270, -1));

        jButton1.setBackground(new java.awt.Color(0, 255, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Ok");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 50, 20));

        TextFieldMovieToAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldMovieToAddActionPerformed(evt);
            }
        });
        jPanel1.add(TextFieldMovieToAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 220, -1));

        OKbtnToAddMovie.setBackground(new java.awt.Color(0, 255, 102));
        OKbtnToAddMovie.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OKbtnToAddMovie.setText("Ok");
        OKbtnToAddMovie.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        OKbtnToAddMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKbtnToAddMovieActionPerformed(evt);
            }
        });
        jPanel1.add(OKbtnToAddMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 50, 20));

        SuccessfulORnot.setForeground(new java.awt.Color(255, 255, 255));
        SuccessfulORnot.setText("Result");
        jPanel1.add(SuccessfulORnot, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        LabelAvailableMoviesList.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelAvailableMoviesList.setForeground(new java.awt.Color(255, 255, 255));
        LabelAvailableMoviesList.setText("Available Movies");
        LabelAvailableMoviesList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(LabelAvailableMoviesList, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        AvailableMoviesList.setBackground(new java.awt.Color(255, 0, 0));
        AvailableMoviesList.setColumns(20);
        AvailableMoviesList.setRows(5);
        AvailableMoviesList.setText("Movie 1\nMovie 2\nMovie 3\nMovie 4\nMovie 5\nMovie 6 \nMovie 7 \nMovie 8 \nMovie 9\nMovie 10\nMovie 11\nMovie 12\nMovies 13\nMovie 14\nMovie 15");
        jScrollPane1.setViewportView(AvailableMoviesList);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 190, 200));

        MoveToAdminTaskPagebtn.setBackground(new java.awt.Color(0, 0, 0));
        MoveToAdminTaskPagebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MoveToAdminTaskPagebtn.setForeground(new java.awt.Color(255, 255, 255));
        MoveToAdminTaskPagebtn.setText("Back");
        jPanel1.add(MoveToAdminTaskPagebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\59510\\Downloads\\required3.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtFieldMovieNameToDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldMovieNameToDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldMovieNameToDeleteActionPerformed

    private void TextFieldMovieToAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldMovieToAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldMovieToAddActionPerformed

    private void OKbtnToAddMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKbtnToAddMovieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OKbtnToAddMovieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aManageMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aManageMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aManageMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aManageMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aManageMovies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AvailableMoviesList;
    private javax.swing.JLabel LabelAvailableMoviesList;
    private javax.swing.JLabel LabelEnterMovieNameToDelete;
    private javax.swing.JLabel LabelEnterMovieNameYouWantToAdd;
    private javax.swing.JLabel LogoToShowADDEDsuccessfullyORnot;
    private javax.swing.JButton MoveToAdminTaskPagebtn;
    private javax.swing.JButton OKbtnToAddMovie;
    private javax.swing.JLabel SuccessfulORnot;
    private javax.swing.JTextField TextFieldMovieToAdd;
    private javax.swing.JTextField TxtFieldMovieNameToDelete;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
