/*



                     This page will appear after clicking the UserWork>Movies Btn



 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guiproject;

/**
 *
 * @author 59510
 */
public class uMovies extends javax.swing.JFrame {

    /**
     * Creates new form uMovies
     */
    public uMovies() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UserLabelAvailableMoviesList = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AvailableMoviesListUser = new javax.swing.JTextArea();
        txtFieldEnterMovieName = new javax.swing.JTextField();
        UserLabelEnterMovieName = new javax.swing.JLabel();
        okBTN = new javax.swing.JButton();
        LabelDetailsShow = new javax.swing.JLabel();
        MoveToUserTaskPagebtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        DetailsShowingTextArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserLabelAvailableMoviesList.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UserLabelAvailableMoviesList.setForeground(new java.awt.Color(255, 255, 255));
        UserLabelAvailableMoviesList.setText("Movies Available :");
        UserLabelAvailableMoviesList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(UserLabelAvailableMoviesList, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        AvailableMoviesListUser.setBackground(new java.awt.Color(204, 0, 0));
        AvailableMoviesListUser.setColumns(20);
        AvailableMoviesListUser.setRows(5);
        AvailableMoviesListUser.setText("Movie 1\nMovie 2\nMovie 3\nMovie 4\nMovie 5\nMovie 6 \nMovie 7 \nMovie 8 \nMovie 9\nMovie 10\nMovie 11\nMovie 12\nMovies 13\nMovie 14\nMovie 15");
        AvailableMoviesListUser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        jScrollPane1.setViewportView(AvailableMoviesListUser);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 180, 230));
        jPanel1.add(txtFieldEnterMovieName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 190, -1));

        UserLabelEnterMovieName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UserLabelEnterMovieName.setForeground(new java.awt.Color(255, 255, 255));
        UserLabelEnterMovieName.setText("Enter Movie Name :");
        UserLabelEnterMovieName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(UserLabelEnterMovieName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        okBTN.setBackground(new java.awt.Color(0, 255, 102));
        okBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        okBTN.setText("Ok");
        okBTN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.add(okBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 70, -1));

        LabelDetailsShow.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelDetailsShow.setForeground(new java.awt.Color(255, 255, 255));
        LabelDetailsShow.setText("Details");
        LabelDetailsShow.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(LabelDetailsShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        MoveToUserTaskPagebtn.setBackground(new java.awt.Color(51, 51, 51));
        MoveToUserTaskPagebtn.setForeground(new java.awt.Color(255, 255, 255));
        MoveToUserTaskPagebtn.setText("Back");
        jPanel1.add(MoveToUserTaskPagebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 20));

        DetailsShowingTextArea.setColumns(20);
        DetailsShowingTextArea.setRows(5);
        DetailsShowingTextArea.setText("Show Time : \nRelease Date :\nTicket Price :\nLast Availability Date :");
        jScrollPane3.setViewportView(DetailsShowingTextArea);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 230, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\59510\\Downloads\\required3.jpg")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new uMovies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AvailableMoviesListUser;
    private javax.swing.JTextArea DetailsShowingTextArea;
    private javax.swing.JLabel LabelDetailsShow;
    private javax.swing.JButton MoveToUserTaskPagebtn;
    private javax.swing.JLabel UserLabelAvailableMoviesList;
    private javax.swing.JLabel UserLabelEnterMovieName;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton okBTN;
    private javax.swing.JTextField txtFieldEnterMovieName;
    // End of variables declaration//GEN-END:variables
}
