/*



                              This page appears after successfull UserLogin


 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guiproject;

/**
 *
 * @author 59510
 */
public class UserWork extends javax.swing.JFrame {

    /**
     * Creates new form UserWork
     */
    public UserWork() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UserTasksLabel = new javax.swing.JLabel();
        UserTask1MoviesRelatedWork = new javax.swing.JButton();
        UserTask2Tickets = new javax.swing.JButton();
        UserTask3SeatsRelatedWork = new javax.swing.JButton();
        UserLogoutBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserTasksLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UserTasksLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserTasksLabel.setText("User's Dashboard");
        UserTasksLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(UserTasksLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        UserTask1MoviesRelatedWork.setBackground(new java.awt.Color(0, 255, 102));
        UserTask1MoviesRelatedWork.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UserTask1MoviesRelatedWork.setText("Movies");
        jPanel1.add(UserTask1MoviesRelatedWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 120, -1));

        UserTask2Tickets.setBackground(new java.awt.Color(0, 255, 102));
        UserTask2Tickets.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UserTask2Tickets.setText("Tickets");
        jPanel1.add(UserTask2Tickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 120, -1));

        UserTask3SeatsRelatedWork.setBackground(new java.awt.Color(0, 255, 102));
        UserTask3SeatsRelatedWork.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UserTask3SeatsRelatedWork.setText("Seats");
        jPanel1.add(UserTask3SeatsRelatedWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 120, -1));

        UserLogoutBtn.setBackground(new java.awt.Color(255, 51, 51));
        UserLogoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UserLogoutBtn.setText("Logout");
        UserLogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserLogoutBtnActionPerformed(evt);
            }
        });
        jPanel1.add(UserLogoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\59510\\Downloads\\required4.jpg")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserLogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserLogoutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserLogoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserWork().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UserLogoutBtn;
    private javax.swing.JButton UserTask1MoviesRelatedWork;
    private javax.swing.JButton UserTask2Tickets;
    private javax.swing.JButton UserTask3SeatsRelatedWork;
    private javax.swing.JLabel UserTasksLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
