/*


                                            Page "1b"
               This page will appear after clicking the User login btn in 1 page 


 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guiproject;

/**
 *
 * @author 59510
 */
public class UserLoginPage extends javax.swing.JFrame {

    /**
     * Creates new form UserLoginPage
     */
    public UserLoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelCMSuserLogin = new javax.swing.JLabel();
        UserUsernamelabel = new javax.swing.JLabel();
        UserUsernameField = new javax.swing.JTextField();
        UserPasswordField = new javax.swing.JPasswordField();
        UserpasswordLabel = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        LoginAsUserBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelCMSuserLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelCMSuserLogin.setText("\"Cinema Management System\"");
        jPanel1.add(LabelCMSuserLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        UserUsernamelabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UserUsernamelabel.setText("Username : ");
        jPanel1.add(UserUsernamelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        UserUsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserUsernameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(UserUsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 180, -1));

        UserPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserPasswordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(UserPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 180, -1));

        UserpasswordLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UserpasswordLabel.setText("Password :");
        jPanel1.add(UserpasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        jProgressBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, 10));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Logging You In...");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        LoginAsUserBtn.setBackground(new java.awt.Color(0, 255, 102));
        LoginAsUserBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LoginAsUserBtn.setText("Login As User");
        LoginAsUserBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        LoginAsUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginAsUserBtnActionPerformed(evt);
            }
        });
        jPanel1.add(LoginAsUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 120, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\59510\\Downloads\\required2.jpg")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserUsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserUsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserUsernameFieldActionPerformed

    private void UserPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserPasswordFieldActionPerformed

    private void LoginAsUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginAsUserBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginAsUserBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCMSuserLogin;
    private javax.swing.JButton LoginAsUserBtn;
    private javax.swing.JPasswordField UserPasswordField;
    private javax.swing.JTextField UserUsernameField;
    private javax.swing.JLabel UserUsernamelabel;
    private javax.swing.JLabel UserpasswordLabel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
